version: '2'

services:
    api:
        image: node:6
        ports:
            - 3000:3000
        volumes:
            - ./:/usr/src
        working_dir: /usr/src/server
        command: npm start
    web:
        image: node:6
        ports:
            - 8000:8000
        links:
            - api
        volumes:
            - ./:/usr/src
        working_dir: /usr/src/client
        command: npm start
