#!/usr/bin/env bash

export USER_ID=$(id -u -r)

./docker/stop
docker-compose up -d

echo "Mockie API is now running at http://localhost:3000"
echo "You can access the client at http://localhost:8000"
