#!/usr/bin/env bash

export USER_ID=$(id -u -r)
export USER_NAME=$(whoami)
export COMMAND="adduser $USER_NAME --uid $USER_ID --disabled-password --gecos ''"

docker run -it --rm --name npm -v "$PWD":/usr/src/app -w /usr/src/app/client node:6 $COMMAND &> /dev/null && cd client && npm "$@"
