#!/usr/bin/env bash

docker run -it --rm --name npm -v "$PWD":/usr/src/app -w /usr/src/app/client/node_modules/.bin node:6 ./webpack --progress --colors --config /usr/src/app/client/webpack.config.js "$@"
